language: node_js
node_js:
  - 8.11.3
cache:
  directories:
    - node_modules
before_script:
  - yarn install
script:
  - yarn build
deploy:
  provider: firebase
  edge:
    source: karthikbalajikb/dpl
    branch: master
  on:
    all_branches: true
  only: 'hosting:development'
  token:
    secure: 'ZDY5GtViRDt5jiw0lqLeVGaR+OEqWczJdsujTfL9qIUmiLLsZowz34XCAn7yuRY82/oxIOTEs252ikjh5l9KWxW1eZ7aH+8TWqh7UHLCSUqWcLgrzZDUp7kwez1gZYdJL7qqvMFLFEmbL/C+Q4M0FxRTRAom/RgqwUHWY9q0lGZjrJUwADvwi4A+hQsdKDKO28ytH3A0i1vjMK7GtO+7N2TQZ+24jYOYuemiaKlzEW1HsaqxwDu9mqcSidwZfnxl8NXN4NIJjeQ+5x94irq/sABgiatNvMr491itMEdQKb0wWlRQUqHbPshWw+N5A8EtMBg/4eIk0qxJ/4qpxF7rLYp9jrjlKrNJh3qjtqXpDkxuPuqVLxvAZRFJnEsskqRkdZzoKpRxqL1G3Irb85RsyeEmV5mGq0/9N9WrcCjkaRkQ4lsk92S7I/9D6MwfU7b6nCqKZF58Q6ucmGt4xhAVd5k1vaV8ISJOHAhzAElJ/5SGFalBKiP8XnBMTeJLFpEG6zidJIsZDX3f/rgTrmhDp4shu5Oz8svWyKIf2Pvfs3b7IXZINEc/aYkd6WjBqy4Upl97oOdi5Wknc/D4CHxd9nJhXxobTMj/nZC5SRx7OTdW8L9gLfIBMCqw5ioq/oDjwhVASiVzDyjhEGs5H4NzedGpvHrOMBbpEE/eufJVBjc='
  message: 'Yooo KB !!! ... KB TechSpace is deployed now'
